services:
  server:
    container_name: backend
    build:
      context: ./app
    ports:
      - 5000:5000
    depends_on:
      db:
        condition: service_healthy
    secrets:
      - db-password
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    develop:
      watch:
        - action: rebuild
          path: ./app/app.py
  db:
    image: postgres:16.1-alpine
    container_name: postgreSql
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=dbpostgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt
